development:
  adapter: postgresql
  username: mexx
  database: confer_development
  pool: 10
  timeout: 5000
  encoding: utf8
  host: localhost

test:
  adapter: postgresql
  username: mexx
  database: confer_test
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
